FROM python:3.9-slim

WORKDIR /app

# Install Streamlit and dependencies
COPY ../api/requirements.txt /app/
RUN pip install -r requirements.txt

# copying API code
COPY ../api /app/

# Run the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false", "--server.headless=true"]
