# Use a lightweight FFmpeg image
FROM jrottenberg/ffmpeg:latest

# Set the working directory
WORKDIR /shared

# RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get update && apt-get install -y ffmpeg 

# Expose a directory to process files (optional)
# VOLUME /app/media

# Default command to show FFmpeg version (replace as needed)
# CMD ["ffmpeg", "-version"]
