# version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile_api
    container_name: docker-api
    volumes:
      - ../api:/app/api  # Mount API folder
      - ../media:/media  # Media storage, shared folder for communication
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/ffmpeg:/usr/local/bin/ffmpeg  # Bind FFmpeg binary
    ports:
      - "8000:8000"  # Expose API on localhost:8000
    depends_on:
      - ffmpeg
    # links:
    #   - ffmpeg
    # networks:
    #   - custom-network

  ffmpeg:
    build:
      context: ..
      dockerfile: docker/Dockerfile_ffmpeg
    container_name: docker-ffmpeg
    volumes:
      - ../media:/media  # Media storage, shared folder for communication
    # ports:
    #   - "8001:5432"
#     networks:
#       - custom-network

# networks:
#   custom-network:
#     driver: bridge
