# Use the lightweight FFmpeg image
FROM jrottenberg/ffmpeg:latest

# Set the working directory
WORKDIR /media

# Expose directory for file processing (optional, depends on your setup)
VOLUME /media

# Default command (optional)
# CMD ["ffmpeg", "-version"]
ENTRYPOINT ["tail", "-f", "/dev/null"]